version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    platform: linux/arm64
    privileged: true
    user: root

    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      - ${PWD}:/workspace
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-awesome-nimbus-452221-v2}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME:-resumatrix-embeddings}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://mlflow:5000}
      - ARTIFACT_REGISTRY_REPO=${ARTIFACT_REGISTRY_REPO:-us-east1-docker.pkg.dev/awesome-nimbus-452221-v2/resume-fit-supervised/xgboost_and_cosine_similarity}

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    container_name: mlflow
    command: mlflow server --host 0.0.0.0
    volumes:
      - mlflow_data:/mlflow

volumes:
  jenkins_home:
  mlflow_data:
