version: '3.8'

services:
  retrainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resumatrix-retrainer
    env_file:
      - ../.env
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5001
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_credentials.json
      - DATA_DIR=/app/data
      - OUTPUT_DIR=/app/data
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME:-resumatrix-embeddings}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./data:/app/data
      - ./model_registry:/app/model_registry
      - ${GCP_JSON_PATH:-/dev/null}:/app/gcp_credentials.json:ro
      - ./mlflow:/app/mlflow
      - ../src:/app/src:ro
    ports:
      - "5000:5000"
    networks:
      - resumatrix-network

networks:
  resumatrix-network:
    driver: bridge
