version: '3.8'

services:
  mlflow:
    image: python:3.12-slim
    container_name: mlflow-server
    command: >
      bash -c "apt-get update && apt-get install -y curl &&
              pip install mlflow>=2.0.0 scikit-learn pandas &&
              mkdir -p /mlflow &&
              export GIT_PYTHON_REFRESH=quiet &&
              export PYTHONUNBUFFERED=1 &&
              echo 'Starting MLflow server...' &&
              mlflow server
              --host 0.0.0.0
              --port 5000
              --backend-store-uri /mlflow
              --default-artifact-root /mlflow"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/2.0/mlflow/experiments/list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - ./mlflow:/mlflow
    ports:
      - "5050:5000"
    networks:
      - resumatrix-network

  retrainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resumatrix-retrainer
    env_file:
      - ../.env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_credentials.json
      - DATA_DIR=/app/data
      - OUTPUT_DIR=/app/data
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME:-resumatrix-embeddings}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./data:/app/data
      - ./model_registry:/app/model_registry
      - ${GCP_JSON_PATH:-/dev/null}:/app/gcp_credentials.json:ro
      - ./mlflow:/app/mlflow
      - ../src:/app/src:ro
    ports:
      - "5051:5000"
    networks:
      - resumatrix-network
    depends_on:
      mlflow:
        condition: service_healthy

networks:
  resumatrix-network:
    driver: bridge
