version: '3.8'

services:
  mlflow:
    image: python:3.12-slim
    container_name: mlflow-server
    command: >
      bash -c "pip install mlflow>=2.0.0 &&
              mkdir -p /mlflow &&
              mlflow server
              --host 0.0.0.0
              --port 5000
              --backend-store-uri /mlflow"
    volumes:
      - ./mlflow:/mlflow
    ports:
      - "5050:5000"
    networks:
      - resumatrix-network

  retrainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resumatrix-retrainer
    env_file:
      - ../.env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_credentials.json
      - DATA_DIR=/app/data
      - OUTPUT_DIR=/app/data
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME:-resumatrix-embeddings}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./data:/app/data
      - ./model_registry:/app/model_registry
      - ${GCP_JSON_PATH:-/dev/null}:/app/gcp_credentials.json:ro
      - ./mlflow:/app/mlflow
      - ../src:/app/src:ro
    ports:
      - "5051:5000"
    networks:
      - resumatrix-network
    depends_on:
      - mlflow

networks:
  resumatrix-network:
    driver: bridge
